baseurl = ""
relativeurls = true
title = "Vigabo AB"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Victor Boivie"

[params]
  DateForm = "Mon, January 2, 2006"
  Description = "Digital Artists since 1981"
  Author = "Victor Boivie"
  email = "info@vigabo.com"
  Ganalytics = "UA-66205660-1"

[[params.social]]
  title = "github"
  url = "https://github.com/vigabo"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/vigabo"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -190
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
